 server:
   port: 9005
 
 spring:
  application:
    name: admin
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MP_DB
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect 

 #message
  app:
   message:Message from application-test.yml 
  
    
  